import React from 'react';
import './LegalPages.css';

const Disclaimer = ({ navigate }) => {
  const lastUpdated = '19 Mar 2026';

  return (
    <div className="legal-container">
      <div className="legal-shell">
        <div className="legal-topbar">
          <div className="legal-brand">
            <img src="/logo.png" alt="Social Stamp logo" />
            <span>Social Stamp</span>
          </div>
          <button className="legal-back" onClick={() => navigate('/')}>Back to Home</button>
        </div>

        <h1 className="legal-title">Disclaimer</h1>
        <p className="legal-meta">Last updated: {lastUpdated}</p>

        <div className="legal-content">
          <p>
            Social Stamp provides AI-generated content. Outputs may be inaccurate, incomplete, or unsuitable for certain uses.
            You are responsible for reviewing and verifying all generated content before publishing or relying on it.
          </p>

          <h2>No professional advice</h2>
          <p>
            Content generated by the Service is provided for informational and creative purposes only and does not constitute
            legal, medical, financial, or other professional advice.
          </p>

          <h2>User responsibility</h2>
          <ul>
            <li><strong>Rights & permissions</strong>: ensure you have rights to any images, scripts, and materials you upload or use.</li>
            <li><strong>Compliance</strong>: comply with local laws, platform rules, and advertising guidelines.</li>
            <li><strong>Review</strong>: verify accuracy of claims, names, and depictions before distribution.</li>
          </ul>

          <h2>AI limitations</h2>
          <p>
            The Service may generate unexpected visuals, voices, or translations. Multi-language talking character videos are
            produced using AI models and may contain occasional lip-sync or pronunciation artifacts.
          </p>

          <h2>Service availability</h2>
          <p>
            We do not guarantee uninterrupted availability, generation times, or specific output quality. Features may change
            or be discontinued.
          </p>

          <h2>Liability</h2>
          <p>
            To the maximum extent permitted by law, Social Stamp is not liable for damages arising from use of the Service,
            including reliance on generated content or distribution of outputs.
          </p>
        </div>

        <div className="legal-divider">
          If you want a more formal Terms of Service page, I can add it too.
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;

